directories:
  output: dist-electron
  buildResources: public
appId: com.gitdense.desktop
productName: GitDense
copyright: Copyright © 2025 GitDense
compression: maximum
files:
  - filter:
      - main.js
      - preload.js
      - dist/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/favicon.ico
  artifactName: GitDense-Setup-${version}.exe
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/favicon.ico
  uninstallerIcon: public/favicon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: GitDense
  perMachine: false
  runAfterFinish: true
  menuCategory: GitDense
mac:
  target: dmg
  icon: public/favicon.ico
linux:
  target: AppImage
electronVersion: 34.5.8
